import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

const searchQuery = "lego"

const defaultEndpoint =
  `https://www.finn.no/api/search-qf?searchkey=SEARCH_ID_BAP_COMMON&abTestKey=controlsuggestions&q=${searchQuery}&sort=PUBLISHED_DESC&page=1&include_filters=false`;

export async function getServerSideProps({ req, res }) {
  res.setHeader(
    "Cache-Control",
    "public, s-maxage=10, stale-while-revalidate=59"
  );

  const r = await fetch(defaultEndpoint);

  const data = await r.json();

  return {
    props: {
      data,
    },
  };
}

export default function Home({ data }) {
  const { results = [] } = data.docs;


  const MINUTE_MS = 60000;

  // useEffect(() => {
  //   const interval = setInterval(() => {
  //     console.log("Reloading");
  //     location.reload();
  //   }, MINUTE_MS);

  //   return () => clearInterval(interval); // This represents the unmount function, in which you need to clear your interval to prevent memory leaks.
  // }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.header}>
          <div><h3 className={styles.title}>Auto-finn</h3></div>
          <div>
            <span><b>Current query:</b> {searchQuery}</span>

            </div>
        </div>
        <div>
        <table className={styles.table}>
        {/* <thead>
          <th>Annonse tekst:</th>
          <th>Lokasjon:</th>
          <th>Pris:</th>
        </thead> */}
        {/* ^^ This will give hydration error ^^ */}
          <tbody>
            <tr>
              <td><b>Annonse tekst:</b></td>
              <td><b>Lokasjon:</b></td>
              <td><b>Pris:</b></td>
              <td><b>Timestamp:</b></td>
            </tr>
            {data.docs.map((data, id) => {
              return (
                <tr key={id}>
                  <td>
                    <a
                      href={`https://www.finn.no/bap/forsale/ad.html?finnkode=${data.ad_id}`}
                      rel="noopener"
                    >
                      {data.heading}
                    </a>
                  </td>
                  <td>{data.location}</td>
                  <td>
                    {JSON.stringify(data.price.amount)}{" "}
                    {JSON.stringify(data.price.currency_code)}
                  </td>
                  <td>{new Date(data.timestamp).toLocaleString("en-GB")}</td>
                </tr>
              );
            })}
          </tbody>
        </table>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
